-- create customers
INSERT INTO dbo.Customer VALUES ('Mike', 'Chandler', GETDATE())
INSERT INTO dbo.Customer VALUES ('Al', 'Fowler', GETDATE())
INSERT INTO dbo.Customer VALUES ('Carl', 'Houston', GETDATE())
INSERT INTO dbo.Customer VALUES ('Evan', 'Dixon', GETDATE())
INSERT INTO dbo.Customer VALUES ('Javier', 'Boone', GETDATE())
INSERT INTO dbo.Customer VALUES ('Jake', 'Gross', GETDATE())
INSERT INTO dbo.Customer VALUES ('Larry', 'Adams', GETDATE())
INSERT INTO dbo.Customer VALUES ('Duane', 'Gilbert', GETDATE())
INSERT INTO dbo.Customer VALUES ('Carroll', 'Shelton', GETDATE())
INSERT INTO dbo.Customer VALUES ('Joanna', 'Alvarez', GETDATE())

-- create products
INSERT INTO dbo.Product VALUES ('Groovestring', '3.95', GETDATE())
INSERT INTO dbo.Product VALUES ('Suntech', '19.81', GETDATE())
INSERT INTO dbo.Product VALUES ('Freshfax', '179.99', GETDATE())
INSERT INTO dbo.Product VALUES ('Stanzap', '99.99', GETDATE())
INSERT INTO dbo.Product VALUES ('Bio-Home', '20125.00', GETDATE())

-- create orders
INSERT INTO dbo.CustomerOrder VALUES (1, GETDATE()) 
INSERT INTO dbo.CustomerOrder VALUES (5, GETDATE()) 
INSERT INTO dbo.CustomerOrder VALUES (2, GETDATE()) 
INSERT INTO dbo.CustomerOrder VALUES (7, GETDATE()) 
INSERT INTO dbo.CustomerOrder VALUES (15, GETDATE())
INSERT INTO dbo.CustomerOrder VALUES (12, GETDATE())
INSERT INTO dbo.CustomerOrder VALUES (1, GETDATE()) 
INSERT INTO dbo.CustomerOrder VALUES (1, GETDATE()) 
INSERT INTO dbo.CustomerOrder VALUES (1, GETDATE()) 
INSERT INTO dbo.CustomerOrder VALUES (7, GETDATE()) 
INSERT INTO dbo.CustomerOrder VALUES (7, GETDATE()) 
INSERT INTO dbo.CustomerOrder VALUES (2, GETDATE()) 

-- create order details
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (1, 5, 1)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (2, 1, 6)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (2, 2, 1)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (3, 3, 1)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (3, 4, 1)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (2, 2, 1)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (4, 2, 3)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (7, 2, 1)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (8, 4, 12)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (9, 1, 1)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (9, 2, 1)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (9, 3, 1)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (9, 4, 1)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (10, 5, 1)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (10, 1, 4)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (11, 3, 1)
INSERT INTO dbo.OrderProduct (CustomerOrderId, ProductId, Quantity) VALUES (12, 4, 6)
